### ISSUE TITLE
application crashes when using BOSHConnection

### ISSUE THREAD

**Issue by maignacio** [rtreffer/asmack#7]
Basically... BOSHConnection's connect() method crashes the application with the following error

```
03-22 15:38:11.343: E/AndroidRuntime(13542): FATAL EXCEPTION: main
03-22 15:38:11.343: E/AndroidRuntime(13542): java.lang.ExceptionInInitializerError
03-22 15:38:11.343: E/AndroidRuntime(13542):    at org.jivesoftware.smack.BOSHConnection.connect(BOSHConnection.java:201)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at com.testapp.xmpptest.XMPPTestActivity.onCreate(XMPPTestActivity.java:36)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.ActivityThread.access$1500(ActivityThread.java:121)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.os.Looper.loop(Looper.java:138)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at android.app.ActivityThread.main(ActivityThread.java:3701)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.lang.reflect.Method.invokeNative(Native Method)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.lang.reflect.Method.invoke(Method.java:507)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at dalvik.system.NativeStart.main(Native Method)
03-22 15:38:11.343: E/AndroidRuntime(13542): Caused by: java.util.regex.PatternSyntaxException: Syntax error U_REGEX_RULE_SYNTAX near index 21:
03-22 15:38:11.343: E/AndroidRuntime(13542): <(?:(?:[^: 
03-22 15:38:11.343: E/AndroidRuntime(13542): 
 >]+:)|(?:\{[^\}>]*?}))?body(?:[    
03-22 15:38:11.343: E/AndroidRuntime(13542): 
 ][^>]*?)?(/>|>)
03-22 15:38:11.343: E/AndroidRuntime(13542):                      ^
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.util.regex.Pattern.compileImpl(Native Method)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.util.regex.Pattern.compile(Pattern.java:400)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.util.regex.Pattern.<init>(Pattern.java:383)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at java.util.regex.Pattern.compile(Pattern.java:374)
03-22 15:38:11.343: E/AndroidRuntime(13542):    at com.kenai.jbosh.ComposableBody.<clinit>(ComposableBody.java:60)
03-22 15:38:11.343: E/AndroidRuntime(13542):    ... 15 more
```

here's my code:

``` java
BOSHConfiguration config = new BOSHConfiguration(true, "host", 80, "/http-bind", "domain");

config.setReconnectionAllowed(true);
config.setSendPresence(false);
Connection connection = new BOSHConnection(config);
try {
    connection.connect();
    connection.login("user", "password");
} catch (Exception e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}
```

**Comment by steveprentice** [comment]
I'm seeing the same issue.

Looks like there is an upstream bug with a possible workaround:
http://kenai.com/jira/browse/JBOSH-24

**Comment by dant3** [comment]
Same here. I were able to use Bosh with changes suggested in JBOSH-24 issue. Here is my patch

```
$ cat patch/42-fix-regexp-compile.patch
--- ../../src-unpatched/trunk/com/kenai/jbosh/ComposableBody.java   2013-07-22 15:09:34.543868532 +0400
+++ com/kenai/jbosh/ComposableBody.java 2013-07-22 15:01:52.643874225 +0400
@@ -58,7 +58,7 @@
      * BOSH message.
      */
     private static final Pattern BOSH_START =
-            Pattern.compile("<" + "(?:(?:[^:\t\n\r >]+:)|(?:\\{[^\\}>]*?\\}))?"
+            Pattern.compile("<" + "(?:(?:[^:\t\n\r >]+:)|(?:\\{[^\\}>]*?}))?"
             + "body" + "(?:[\t\n\r ][^>]*?)?" + "(/>|>)");

     /**
```

**Comment by huhai1986** [comment]
how to set connection timeout?
